---
  - name: Update apt
    become: yes
    apt:
      update_cache: yes

  - name: Upgrade apt
    become: yes
    apt:
      upgrade: yes

  - name: Remove dependencies that are no longer required
    become: yes
    apt:
      autoremove: yes

  - name: Install nodejs and npm
    become: yes
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: Install n
    become: yes
    npm:
      name: n
      global: yes
      production: yes

  - name: Install nodejs 13.8.0
    become: yes
    shell: n 13.8.0

  - name: Install pm2
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present
